### ISSUE TITLE
Catch Solidity emitted events and show in Console window

### ISSUE THREAD

**Issue by parrisma** [parrisma/distledge#28]
For the demo we need to be able to see the solidity events coming back to the UI as pop-ups and lines in console window.

This will be done when I can demo any one emitted event from any solidity contract being caught by its corresponding component and shown as a UI pop up and a message line in console window

**Comment by thatjamie** [comment]
Two probs to resolve:

1. The useEffect hook is not awaiting for the async function to complete for neccessary info
2. Looks like onAddInfo hook printing logs to console is not capturing every event
